# Cloudflare Pages configuration
name = "sinister-dexter"
compatibility_date = "2024-08-03"
pages_build_output_dir = "public"

# Environment variables (if needed for future features)
[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }