name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Skip HEIC conversion and image processing in CI - images are pre-processed
      # and committed to the repository. This saves ~2 minutes of build time.

      - name: Build HTML
        run: npm run build:html

      - name: Deploy to Cloudflare Pages (Staging)
        if: github.event_name == 'pull_request'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sinister-dexter
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: preview-${{ github.event.pull_request.number }}
          wranglerVersion: '3'

      - name: Deploy to Cloudflare Pages (Production)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sinister-dexter
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          wranglerVersion: '3'

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `🎸 **Sinister Dexter Preview Deployment**
            
            Your changes have been deployed to: https://preview-${{ github.event.pull_request.number }}.sinister-dexter.pages.dev/
            
            Please review the preview before merging to main.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })