name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write  # Required for PR comments
      issues: write         # Required for issue comments
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Skip HEIC conversion and image processing in CI - images are pre-processed
      # and committed to the repository. This saves ~2 minutes of build time.

      - name: Build HTML
        run: npm run build:html

      - name: Deploy to Cloudflare Pages (Staging)
        if: github.event_name == 'pull_request'
        id: cloudflare-deploy
        run: |
          OUTPUT=$(npx wrangler@3 pages deploy public \
            --project-name=sinister-dexter \
            --branch=preview-${{ github.event.pull_request.number }} \
            --commit-dirty=true 2>&1)
          echo "$OUTPUT"
          DEPLOYMENT_URL=$(echo "$OUTPUT" | grep -oP 'https://[a-z0-9]+\.sinister-dexter\.pages\.dev' | head -1)
          echo "deployment-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "Deployment URL: $DEPLOYMENT_URL"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Pages (Production)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          npx wrangler@3 pages deploy public \
            --project-name=sinister-dexter \
            --branch=production \
            --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request' && steps.cloudflare-deploy.outputs.deployment-url
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = '${{ steps.cloudflare-deploy.outputs.deployment-url }}';
            const branchUrl = `https://preview-${{ github.event.pull_request.number }}.sinister-dexter.pages.dev/`;
            const comment = `🎸 **Sinister Dexter Preview Deployment**
            
            ✅ **This build**: ${deploymentUrl}
            🔄 **Latest on PR**: ${branchUrl}
            
            Commit: \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
            
            The first link shows this exact build, while the second always shows the latest changes on this PR.`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })