name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Convert HEIC images (if any)
        run: |
          # Install ImageMagick for HEIC support on Linux
          sudo apt-get update
          sudo apt-get install -y imagemagick libheif-examples
          
          # Convert HEIC files to JPG
          for file in photos/*.HEIC photos/*.heic; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" | sed 's/\.[^.]*$//')
              heif-convert "$file" "photos/${filename}_converted.jpg"
            fi
          done
        continue-on-error: true

      - name: Process images
        run: npm run process-images

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sinister-dexter
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref == 'refs/heads/main' && 'main' || github.head_ref }}
          wranglerVersion: '3'